import type { Metadata } from 'next'
import { IBM_Plex_Sans, Montserrat } from 'next/font/google'

import { ThemeProvider } from '@/components/theme-provider'
import { cn } from '@/lib/utils'

import './globals.css'

const montserratHeading = Montserrat({ subsets: ['latin'], variable: '--font-heading' })

const ibmPlexSans = IBM_Plex_Sans({ subsets: ['latin'], variable: '--font-sans' })

export const metadata: Metadata = {
  title: 'Master Template',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={cn(ibmPlexSans.variable, montserratHeading.variable, 'antialiased')}
    >
      <body className="min-h-screen min-w-screen font-sans bg-primary">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <header className="font-heading font-bold">Pagina Inicial</header>
          <main>{children}</main>
          <footer>
            <p>pata</p>
          </footer>
        </ThemeProvider>
      </body>
    </html>
  )
}
